### ISSUE TITLE
macOS: PlatformException on Hot Restart 

### ISSUE THREAD

**Issue by ToniTornado** [pichillilorenzo/flutter_inappwebview#2405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run the example application on macOS and perform a hot restart, I get the following exception:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(recreating_view, trying to create an already created view, view id: '0', null)`

### Expected Behavior

The widget tree is rebuilt and a fresh instance of `InAppWebView` is created without throwing an exception. 

### Steps with code example to reproduce

<details>
<summary>Steps with code example to reproduce</summary>

```dart
// Paste your code here
```
</details>

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
<Replace this line by pasting your stacktrace or logs here>
```
</details>

### Flutter version

3.24.4

### Operating System, Device-specific and/or Tool

macOS

### Plugin version

6.2.0-beta.1

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
For unknown reasons, the Flutter PlatformView is not disposed automatically on Hot Restart.
It works as expected on Android, iOS and Windows but not macOS.
i think this is has something to do on how Flutter manages the native PlatformView under the hood as this plugin is using the Flutter official API to render native views.
Probably, you should open an issue on the Flutter official repo and you can mention this issue.

**Comment by hhcme** [comment]
I also found similar issues in my project

**Comment by giorgiogross** [comment]
Experiencing the same issue; wasn't aware it only happens on hot restart but a full rebuild helps

**Comment by PaulAllanSturm** [comment]
> For unknown reasons, the Flutter PlatformView is not disposed automatically on Hot Restart. It works as expected on Android, iOS, and Windows but not on macOS. I think this has something to do with how Flutter manages the native PlatformView under the hood as this plugin is using the Flutter official API to render native views. Probably, you should open an issue on the Flutter official repo and you can mention this issue.

Here is the relevant issue in the Flutter repo: https://github.com/flutter/flutter/issues/110381

A particular problem with using PlatformView and Hot Restart on macOS has been fixed. The fix is only on the main branch right now. I'm not entirely certain that fix will address this issue here, but it would be worth retesting against the Flutter main branch.

**Comment by LefebvreIlyas** [comment]
Hello @PaulAllanSturm,

Thank you for your PR! I just tried unfortunately the problem is still present 😢 (cc #2504)

`Flutter (Channel master, 3.30.0-1.0.pre.544, on macOS 15.3.1 24D70`

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(recreating_view, trying to create an already created view, view id: '0', null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:370:18)
<asynchronous suspension>
#2      PlatformViewsService.initAppKitView (package:flutter/src/services/platform_views.dart:282:5)
<asynchronous suspension>
#3      _DarwinViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:933:36)
<asynchronous suspension>
```

**Comment by lllyin** [comment]
@LefebvreIlyas I switched to the master channel, and it works.
